import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Venkatesh",
      email: "admin@example.com",
      password: bcrypt.hashSync("password", 8),
      isAdmin: true,
    },
    {
      name: "Rishabh",
      email: "user@example.com",
      password: bcrypt.hashSync("password", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: "3.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Adidas",
      rating: "3.0",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 0,
      brand: "UCB",
      rating: "4.0",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fit Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 420,
      countInStock: 5,
      brand: "Arrow",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Slim Fit",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 320,
      countInStock: 10,
      brand: "Mufti",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Slim Fit",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 520,
      countInStock: 0,
      brand: "Puma",
      rating: "4.0",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fit Jeans",
      category: "Jeans",
      image: "/images/p7.jpg",
      price: 720,
      countInStock: 0,
      brand: "Puma",
      rating: "4.0",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Slim Jeans",
      category: "Wrangler",
      image: "/images/p8.jpg",
      price: 920,
      countInStock: 0,
      brand: "Wrangler",
      rating: "4.0",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fit Jeans",
      category: "Wrangler",
      image: "/images/p8.jpg",
      price: 920,
      countInStock: 0,
      brand: "Wrangler",
      rating: "4.0",
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
